# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVupnlAXlCvnpSApyH5wYBylCOtXh-Cr
"""

# =====================================================
# IMPORTS
# =====================================================
import pandas as pd
import geopandas as gpd
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
import plotly.graph_objects as go

# =====================================================
# LOAD DATA (COUNTY LEVEL)
# =====================================================
df = pd.read_csv("gvsudegree_clean.csv")

df['Graduated'] = pd.to_numeric(df['Graduated'], errors='coerce').fillna(0)

# =====================================================
# SPLIT DATA
# =====================================================
us_df = df.dropna(subset=['stfip']).copy()
out_us_df = df[df['stfip'].isna()].copy()

# Clean FIPS
us_df['stfip'] = us_df['stfip'].astype(int).astype(str).str.zfill(2)
us_df['fips'] = us_df['fips'].astype(str).str.zfill(5)

# =====================================================
# 🔥 STATE AGGREGATION (MAP 1)
# =====================================================
state_df = us_df.groupby('stfip', as_index=False)['Graduated'].sum()
out_us_total = out_us_df['Graduated'].sum()

# =====================================================
# LOAD STATES
# =====================================================
states = gpd.read_file(
    "https://www2.census.gov/geo/tiger/GENZ2020/shp/cb_2020_us_state_20m.zip"
)

states = states.to_crs(epsg=4326)
states['stfip'] = states['STATEFP'].astype(str).str.zfill(2)

state_map = states.merge(state_df, on='stfip', how='left')
state_map['Graduated'] = state_map['Graduated'].fillna(0)

state_geojson = state_map.__geo_interface__

# =====================================================
# 🔥 MICHIGAN COUNTY MAP (MAP 2)
# =====================================================
counties = gpd.read_file(
    "https://www2.census.gov/geo/tiger/GENZ2020/shp/cb_2020_us_county_20m.zip"
)

mi_counties = counties[counties['STATEFP'] == '26'].copy()
mi_counties['GEOID'] = mi_counties['STATEFP'] + mi_counties['COUNTYFP']
mi_counties = mi_counties.to_crs(epsg=4326)

# Aggregate county-level
county_df = us_df.groupby('fips', as_index=False)['Graduated'].sum()

mi_map = mi_counties.merge(county_df, left_on='GEOID', right_on='fips', how='left')
mi_map['Graduated'] = mi_map['Graduated'].fillna(0)

mi_geojson = mi_map.__geo_interface__

# =====================================================
# APP
# =====================================================
app = Dash(__name__)
server = app.server

app.layout = html.Div([

    html.H2("Graduates Geographic Dashboard"),

    html.Div([

        # ================= US MAP =================
        html.Div([
            html.H4("US Distribution (State Level)"),
            dcc.Graph(id='us_map')
        ], style={
            'width': '48%',
            'display': 'inline-block',
            'padding': '10px',
            'border': '2px solid #ccc',
            'borderRadius': '10px'
        }),

        # ================= MI MAP =================
        html.Div([
            html.H4("Michigan Distribution (County Level)"),
            dcc.Graph(id='mi_map')
        ], style={
            'width': '48%',
            'display': 'inline-block',
            'padding': '10px',
            'border': '2px solid #ccc',
            'borderRadius': '10px'
        })

    ])

])

# =====================================================
# BUILD FIGURES
# =====================================================
def create_us_map():
    fig = go.Figure()

    fig.add_trace(go.Choropleth(
        geojson=state_geojson,
        locations=state_map['stfip'],
        z=state_map['Graduated'],
        featureidkey="properties.stfip",
        text=state_map['NAME'],
        colorscale="Blues",
        hovertemplate="<b>%{text}</b><br>Graduated: %{z:,}<extra></extra>"
    ))

    # Out-of-US bubble
    fig.add_trace(go.Scattergeo(
        lon=[-130],
        lat=[25],
        text=[f"Out of US<br>{out_us_total:,}"],
        mode='markers+text',
        marker=dict(
            size=(out_us_total ** 0.5) * 1.5,
            color='red'
        ),
        textposition="top center",
        showlegend=False
    ))

    fig.update_geos(fitbounds="locations", visible=False)

    fig.update_layout(height=600, margin={"r":0,"t":40,"l":0,"b":0})

    return fig


def create_mi_map():
    fig = go.Figure()

    fig.add_trace(go.Choropleth(
        geojson=mi_geojson,
        locations=mi_map['GEOID'],
        z=mi_map['Graduated'],
        featureidkey="properties.GEOID",
        text=mi_map['NAME'],
        colorscale="Blues",
        hovertemplate="<b>%{text}</b><br>Graduated: %{z:,}<extra></extra>"
    ))

    fig.update_geos(fitbounds="locations", visible=False)

    fig.update_layout(height=600, margin={"r":0,"t":40,"l":0,"b":0})

    return fig

# =====================================================
# CALLBACK
# =====================================================
@app.callback(
    [Output('us_map', 'figure'),
     Output('mi_map', 'figure')],
    []
)
def update_maps():
    return create_us_map(), create_mi_map()

# =====================================================
# RUN
# =====================================================
if __name__ == "__main__":
    app.run_server(host="0.0.0.0", port=8050)
